### ISSUE TITLE
"The Old Ones" on music page not showing status correctly

### ISSUE THREAD

**Issue by zertap** [weirdgloop/WikiSync#11]
As title says. Wiki says I need Box of Delights and The Old Ones when ingame I only need the Box of Delights.

**Comment by andmcadams** [comment]
Thanks for the reminder. I know we need to update the server side for the new quest but would have forgot about the track. Hopefully this will be updated today.

**Comment by andmcadams** [comment]
Closing out stale issue, this was fixed a while back but I forgot to close it out
