### ISSUE TITLE
Natural History Quiz mini quest cannot be auto marked as completed on wiki

### ISSUE THREAD

**Issue by VonSprocket** [weirdgloop/WikiSync#12]
As explained in title.

I have completed this mini quest and the osrs wiki quest guide page does not mark this quest as completed after pressing lookup on my username.

Thank you

**Comment by andmcadams** [comment]
Super late reply, but just cleaning up some issues. This isnt supported and doesn't require a change to this code, but we could support it as part of https://github.com/weirdgloop/wikisync-api/issues/45 .
