### ISSUE TITLE
how can i query player wiki information?

### ISSUE THREAD

**Issue by AnthonyPoschen** [weirdgloop/WikiSync#19]
looking to access the combat achievements of clan members is it possible to get data of what combat achievements are completed from the api outside of a list of numbers correseponding to the order it appears on the wiki page. as that will require lots of unecceasy web scraping to achieve and be fickle. really just looking for a way to calculate the points total for a player and what tier that puts them at without needing to web scrape the wiki web page as well.

**Comment by lezed1** [comment]
Unfortunately, accessing WikiSync data by anything other than the OSRS Wiki is not permitted. Source: https://oldschool.runescape.wiki/w/RuneScape:WikiSync#Third-party_use

If you want to collect this data for a clan, maybe you could fork the WikiSync plugin, run a server to store the data, and ask clan members to install your version? I know this is not the most helpful suggestion, but it's the best idea we could come up with!
