### ISSUE TITLE
Remove account data

### ISSUE THREAD

**Issue by notSoWiseOldMan** [weirdgloop/WikiSync#23]
Hi I am curious if there is a way to remove my accounts data from wiki sync. I would like other users not to be able to look me up beyond what the hi scores makes available.

Thanks!

If there is a better place for questions please let me know

**Comment by andmcadams** [comment]
Hey! Feel free to either leave the usernames you want cleared here, or message me `@andmcadams` or `@cookmeplox` on discord. We can get it sorted for you

**Comment by notSoWiseOldMan** [comment]
shelt3r

Thanks!

**Comment by andmcadams** [comment]
Should be removed now
