### ISSUE TITLE
Request: Store Music Unlocks

### ISSUE THREAD

**Issue by Ferrariic** [weirdgloop/WikiSync#3]
This information would be useful for those looking to unlock music tracks, allowing for automatic filtering of locked and unlocked tracks on the wiki. 

This would also be useful from a wiki-perspective to see what music tracks are commonly unlocked by players, and the least commonly unlocked music tracks.

**Comment by andmcadams** [comment]
We actually have the capability for this now, but there isn't really a compelling use case (afaik) on the wiki for this. We don't want to use this project to aggregate data on players since that isn't really what they are signing up for here. We actually already do gather music unlocks (indirectly) via crowdsourcing.

If there's a good use case for this on wiki, I would be interested in exploring it though.

**Comment by Brentjtaylor** [comment]
> 

Hey mate, I just came here to make essentially the exact same post minus the commonly unlocked tracks.

PLEASE ADD THIS.

I have only 40 songs to go, and I was going to go for the music cape today but then I realised I would have to filter through **675 songs manually**.


If you already have the capability, **please please add this**. It would make life so much easier if it automatically highlighted the ones you've finished on the wiki.

**Comment by andmcadams** [comment]
Just to clarify, the **plugin** already has the capability to transmit this data (music unlocks are just stored in varps), but there is a decent chunk of work that would need to be done on the wiki side of things. Most likely what we would do is something similar to the leagues tasks, where we highlight ones you already have.

**Comment by Brentjtaylor** [comment]
> 

Yeh that's essentially exactly what I'm asking for.

Just like how when you click on a music track it highlights it green, ideally it'd highlight all of your completed tracks green automatically.

I think it'd definitely be beneficial as well as being probably one of the most useful functions it can offer.

**Comment by Brentjtaylor** [comment]
Any update?

**Comment by andmcadams** [comment]
Nope. There are other things about the plugin that we are trying to change that have much higher priority right now.

**Comment by leejt** [comment]
This is implemented now at https://oldschool.runescape.wiki/w/Music
