### ISSUE TITLE
Security: Enable Jagex Name Authorization on wiki-search for RuneLite Lookup

### ISSUE THREAD

**Issue by Ferrariic** [weirdgloop/WikiSync#5]
Recommended Security changes:

- Bound string limits to `1-12` (Inclusive)
- Allow `A-Za-z0-9`
- Allow `-_ `

Consider name normalization to all lowercase and replace dashes (-) and spaces with underscores - if not completed already. 

This should be performed on the API endpoint. 

Test Cases:
Entry `11111111111111111111111111111111111` returns 
![image](https://user-images.githubusercontent.com/5789682/149691804-34f6cc76-19ba-45ac-88cd-c7000fbedfe8.png)

Entry `\\\\\\\` returns
![image](https://user-images.githubusercontent.com/5789682/149692013-823d7eb6-4b9f-447f-9f76-f71a5708bdf4.png)

No Entry returns
![image](https://user-images.githubusercontent.com/5789682/149692343-2a872668-c838-4c0e-8b25-09cbe1ae7d43.png)

It should be recommended to return a HTTP 400 with a detail of `Invalid RSN` for all invalid checks. Regex check would include `[\w\d\s_-]{1,12}`

**Comment by leejt** [comment]
This isn't really a security suggestion. There are checks and normalizations related to this at a server level. I don't think it matters whether we return a "no data" or "invalid RSN", and I think it would be a mistake to over-index on what characters are currently allowed in usernames.
