### ISSUE TITLE
Karamja Diary incorrectly swapped tasks

### ISSUE THREAD

**Issue by IanBurgan** [weirdgloop/WikiSync#6]
I believe the charter ship tasks in the medium diary may be swapped. After doing a fresh lookup, the wiki correctly shows that one is complete, and that the other is not. However, it shows the wrong charter ship task as complete with the other one incorrectly shown as incomplete. Screenshots included for clarity:

**Shown complete on the wiki, but is not actually complete in game**
<img width="375" alt="image" src="https://user-images.githubusercontent.com/18379939/158733379-628a5dd8-124d-412c-8b94-3edf2cc22ca8.png">
<img width="319" alt="image" src="https://user-images.githubusercontent.com/18379939/158733462-94761393-9422-442a-b9d5-9b0dbaff54bf.png">

**Shown incomplete on the wiki, but is actually complete in game**
<img width="376" alt="image" src="https://user-images.githubusercontent.com/18379939/158733560-c2f6e32e-d488-4d67-b98b-030e41815a3f.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/18379939/158733588-9ded7134-588e-40a5-a323-0b0d584a7835.png">

**Comment by leejt** [comment]
This should be fixed now.
