### ISSUE TITLE
CORS preventing oldschool.runescape.wiki from reading API

### ISSUE THREAD

**Issue by binbendo-crabo** [weirdgloop/WikiSync#8]
When clicking the Runelite "Look up" button on the wiki:
![image](https://user-images.githubusercontent.com/68548981/171056849-9693191b-382f-42a5-a7a9-bd4d44ca977b.png)
the request is blocked because its response does not have a Access-Control-Allow-Origin CORS header
![image](https://user-images.githubusercontent.com/68548981/171056734-1dc2cf10-2a7b-4298-93e8-f37cfbeb4b03.png)
resulting in a failure to load data.
![image](https://user-images.githubusercontent.com/68548981/171056799-8cacef17-848a-486d-ae9f-15a5b9dd0b4f.png)

I'm using Firefox version 100.0.2, but I get the same problem using Chrome.

**Comment by andmcadams** [comment]
Thanks for reporting, I think we have identified the problem and are working on fixing it. Will update here once we have made progress.

**Comment by andmcadams** [comment]
Looks to be all good now. @bria-bloom if you can confirm it's working again for you I'll go ahead and close this now. Otherwise I'll give it a few hours

**Comment by binbendo-crabo** [comment]
Yep, this fixed it! thanks!
