### ISSUE TITLE
Quest grabber bug

### ISSUE THREAD

**Issue by Footbender** [weirdgloop/WikiSync#9]
My quest grabber is failing to properly pull my completed quests. Below is my specific example, but I will monitor for more and update

**Name:** Fade_Maze
**Account Type:** P2P Ironman
**Quest:** Shield of Arrav
**Issue:** Quest is marked as incomplete when checking requirements for further quests

This issue can be verified by checking any quest that is 2 nest levels above **Shield of Arrav**. For example, when validating my eligibility for **Legends' Quest**, the API will return *true* for **Heroes' Quest** but returns *false* for the nested required quest **Shield of Arrav**

This issue is also noted with a similar check on eligibility for **Recipe for Disaster**. This quest requires **Shield of Arrav** to be completed, but the requirement checker still returns a *false* result for **Shield of Arrav**, leading me to believe this specific quest checker is broken. The screenshot below shows that I actually have both quests complete

![image_2022-08-20_102650687](https://user-images.githubusercontent.com/111654265/185759196-13d7e5da-20f8-4c39-b3cb-2c7b301c83a6.png)

**Comment by Footbender** [comment]
Attempted uninstall and reinstall of plugin, no implovement

**Comment by andmcadams** [comment]
Yeah, this is a known issue from when Jagex refactored some special case quests unfortunately. I'm hoping to get around to fixing some music track issues soon so I can fix this then too. I had forgot about this one though so thanks for bringing it up!

**Comment by leejt** [comment]
This should be fixed now.
